---
title: "02_Statistical_Learning"
author: "Hamidou Ballo"
date: "2023-06-25"
output: html_document
---

## 2.3 Lab Introduction to R:

### 2.3.1 Basic Commands:

set.seed(1303)

rnorm(50)

```{r}
# Using the function concatenate to get a vector
x <- c(1, 3, 2, 5)
x 

# Assagning things using the = operator.
x = c(1, 6, 2)
x
y = c(1, 4, 3)

# Hitting the up arrow will show you the previous command you ran.
# We can add two vectors, but they have to be the same length.
length(x)
length(y)
x + y

# Try using arrays of different length. The extra element is added to the first item in x. And there where more than one the second extra item will be added the second item in the vector x.
z = c(5, 4, 9, 1)
x + z

# ls() function allows us allows us to see the objects we have so far and rm() is 
# for removing those objects.
ls()
rm(x, y, z)
ls()

# It is also possible to remove all objects at once.
rm(list = ls())

# We also have the matrix function which allows us to make matix of numbers:
?matrix # To learn more about matrix

# It has many arguments but we want to focus on the first three(data or entries, 
# number of rows, number of columns).
x <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)
x

# we can ommit ( data , nrow and ncol)
x <- matrix(c(1, 2, 3, 4), 2, 2)

# It is sometimes useful to use the name because R expect the arguments to be passed in the same order in the help.
matrix(c(1, 2, 3, 4), 2, 2, byrow = TRUE) # byrow allows to start by filling the 
# rows first.
# We didn't assign the matrix to any value.

# The sqrt() returns the square root of each items in the matrix, and x^2 squares eanch item.
sqrt(x)
x^2

# The rnorm() gives us a vector of random normal variables. Here we use two vectors generated by rnorm to fing the coration between two sets.
x <- rnorm(50)
y <- rnorm(50, mean = 50, sd = .1)
x 
y
cor(x, y)

# The default mean is 0 and the standard deviation is 1. We can later that using mean and sd arguments. In order to reproduce the same random selection we use set.seed() and give it an integer as an argument.
set.seed(1303) 
rnorm(50)

# We also have the mean() and var() used to compute the mean or variance of a 
# vector. In order to find the standard deviation, we can either use sqrt() on the 
# variance or use the sd() function.
set.seed(3)
y <- rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```

### 2.3.2 Graphics:

```{r}
# In oder to plot we use the plot() function, using plot(x, y) makes a scatter plot fo x versus y. Using the xlab arguments allows us to set the x label of the plot. 
?plot # To learn more about plots.
x <- rnorm(100)
y <- rnorm(100)
plot(x, y)
plot(x, y, xlab = "this is the x-axis",
     ylab = "this is the y-axis",
     main = "Plot of X versus Y")

# In oder to save the output of an R plot we can use pdf()(pdf file) or jpeg() 
# (jpeg file) function.
pdf("Figure.pdf")
plot(x, y, col = "green")
dev.off() # This is notifying R that we are done plotting. We could have also 
# copied and pasted the plot window in the appropriate file type.

# The function seq(a, b) is used to make sequences of numbers between a and b.
# another option is seq(0, 1, length = 10) make a sequence of 10 numbers that are 
# equally spaced between 0 and 1. Typing 3:11 is short for seq(3, 11)
x <- seq(1, 10)
x 
x <- 1:10
x 
x <- seq(-pi, pi, length = 50)
x

# To create more sophisticated plots we use the contour() function which allows us 
# to plot 3-dimentional data. It take three arguments like a topographical map.
# ( a vector of x values for the first dimension, a vector of y values for the 
# second dimension, and a matrix whose elements correcpond to the 3rd dimention for # each pair of (x, y) coordinates).
y <- x
f <- outer(x, y, function(x, y) cos(y) / (1 + x^2))
contour(x, y, f)
contour(x, y, f, nlevels = 45, add = T)
fa <- (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)

# The image() function achieve the same as countour except it adds colored coded pot whos color depends on the z value. We can also use the persp() for 3D plots the arguments theta and phi sets the view angle of the plot.
image(x, y, fa)
persp(x, y, fa)
persp(x, y, fa, theta = 30)
persp(x, y, fa, theta = 30, phi = 20)
persp(x, y, fa, theta = 30, phi = 70)
persp(x, y, fa, theta = 30, phi = 40)
```

### 2.3.3 Indexing Data

```{r}
# In order to get access to a portion of the data in matrix A we can do this.
A <- matrix(1:16, 4, 4)
A
A[2, 3] # second row third column.

# Select multiple rows and column by passing vectors as the indices.
A[c(1, 2), c(2, 4)]
A[1:3, 2:4] 
A[1:2, ] 
A[, 1:2]
# The last two select every rows or column because it is not specified. R treats a # single row or column of a Matrix as a vector.
A[1, ]

# Negative indexing allows us to keep all the rows except the ones mentionend in 
# the vector.
A[-c(1, 3), ]
A[-c(1, 3), -c(1, 3, 4)]

# The dim() prints the number of rows followed by the number of column in agiven 
# matrix
dim(A)
```

### 2.3.4 Loading Data

```{r}
# We have the read.table() function, which import data into R and the write.table 
# function which allows us to export data.
library(readr)
Auto <- read.table("Auto.data") 
View(Auto) # The whole table.
head(Auto) # cople rows in the dataset.

# It is advised to look into files your importing in R before lading them. This on has issues. One R thinks the variable names are part of the data set. Two There are somone rows with "?" in our data set indicating missing values. To solve these problems we do the following:
Auto <- read.table("Auto.data", header = T, na.strings = "?", stringsAsFactors = T)
View(Auto) 
# header = T or TRUE tells R that the first row is for the table variable.
# na.strings= "?" means anytime I see "?" this will bel represented as a missing 
# value.
# stringsAsFactors = T tells R that any variable containing characters is treated a # qualitative variable.

# Loading Data from excel into R another way.
Auto <- read.csv("Auto.csv", na.strings = "?", stringsAsFactors = T)
View(Auto)

dim(Auto) # We have 397 observations or rows and 9 variables or columns.

# na.omit() to remove rows with missing values there is 5 in the Auto dataset
Auto <- na.omit(Auto)
dim(Auto)

# After properly loading the date we can do things like getting all the variable 
# names using the names() function
names(Auto)
```

### 2.3.5 Additional Graphical and Numerical Summaries:

```{r}
# In order to plot variable from the Auto data, you need to use the $ to secify 
# where the varible is comming from. Not doing so leads to an error.
plot(cylinders, mpg) # ERROR
# Right way
plot(Auto$cylinders, Auto$mpg)
# Achiving the same thing using attach() function.
attach(Auto)
plot(cylinders, mpg)

# The cylinders variable is curenlty treates as a quantitative variable. In order 
# to change it from a quantitative to a qualitative variable we use the as.factor() # function.
cylinders <- as.factor(cylinders) # Its a factor with 5 levels(categories)

# The plot function automatically plots a boxplot if the x axis is a qualitative variable. Ther is multibple option to choose from when plotting.
plot(cylinders, mpg)
plot(cylinders, mpg, col = "red")
plot(cylinders, mpg, col = "red", varwidth = T)
plot(cylinders, mpg, col = "red", varwidth = T, horizontal = T) 
plot(cylinders, mpg, col = "red", varwidth = T, xlab = "cylinders", ylab = "mpg")

# The hist() function plots histograms. col = 2 has the same effect as col = "red".
hist(mpg)
hist(mpg, col = 2)
hist(mpg, col = 2, breaks = 15)

# The pairs() function produces a scatterplot matrix for every pair of variables or
# a subset of variables
pairs(Auto)
pairs(
  ~ mpg + displacement + horsepower + weight + acceleration , data = Auto
)

# Allows you to click # one or multiple points in the plot and see the name value 
# associatied with each
# observation.
plot(horsepower, mpg)
identify(horsepower, mpg, name)

# The summary function prosuces an numerical summary of each variable in a data set
#.
summary(Auto) # Quantitave variables summary includes the number of observations 
# that fall in each category.
summary(mpg) # Getting the summary of only one column(variable , feature).

q() # To quit R
savehistory() # To save all the objects that we made for when we come back
loadhistory() # To load the savesd objects.
```

## 2.4 Exercises
